### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jmsong2** [hiclib/pastis#30]
Hi all,
I uesd the follow command to install and test Pastis:
```
git clone https://github.com/hiclib/pastis/
pip install pastis
cd pastis/examples/pastis_example/
pastis-mds .
```
but I got the follow error.
```
Traceback (most recent call last):
  File "/home/anaconda2/bin/pastis-mds", line 4, in <module>
    from pastis.algorithms import run_mds
ImportError: No module named algorithms

```
Could you give me some suggestion?
Thanks a lot!

Regards,
Jiaming

**Comment by NelleV** [comment]
Hi @jmsong2 
I'm terribly sorry… I seem to have missed a large number of issues opened on pastis.
I think since then I've released a new version. It may fix the issue. Do you mind trying to update pastis?
Many thanks,
Nelle

**Comment by jmsong2** [comment]
Hi Nelle,
Thanks for your reply, I will try to update it.

Regards,
Jiaming

**Comment by NelleV** [comment]
So the version I released two weeks ago had the same issue, but I finally tracked down the problem. Version 0.3.3 fixes these installation problems. It may take a couple of hours for the release to propagate.
Thanks!
