### ISSUE TITLE
Website/install: When you use 'pip' you don't get src/MDS and src/PM

### ISSUE THREAD

**Issue by HenrikBengtsson** [hiclib/pastis#4]
If you use Anaconda and

``` sh
pip install pastis
```

to install PASTIS (as suggested on http://cbio.ensmp.fr/~nvaroquaux/pastis/install.html), then you won't get the source.   In such case, Section 'MDS_ALL/PM_ALL' is unclear because src/MDS and src/PM are nowhere to be found.  You probably want to clarify this.

**Comment by NelleV** [comment]
That issue should be fixed as well in the next release. I'll close once I'm sure pip works fine.

Thanks for reporting all of these!

**Comment by NelleV** [comment]
Now that I've moved to a full python implementation, this is no longer the case.
I just need to do a proper release on pypi.
