### ISSUE TITLE
Simulating HiC data

### ISSUE THREAD

**Issue by tarak77** [hiclib/pastis#47]
Hi Nelle,

Thanks for the HiC data simulation code from the 3D coordinates. The example script works well on the given yeast genome data, I also reconstructed a contact matrix from the output coordinates obtained from a mouse single cell data (Setting alpha=-3 and a large beta so as to avoid generating very sparse data)

Will the reconstructed contact matrix in this case be comparable with the original contact matrix? Th parameter alpha=-3 is obtained by relating distances with the contact count, but since single cell data does not have contact frequencies, I wonder how relevant the alpha parameter is? I am finding it difficult to convince myself.

Any help will be great!

Thanks,
Tarak

**Comment by NelleV** [comment]
Sorry… i totally missed this ticket.
It's hard to say: the data you are using probably doesn't follow a poisson distribution, so you might be better using a whole other way to simulate data than the one I used.
