### ISSUE TITLE
SUGGESTION: Locate IPOPTPATH automagically

### ISSUE THREAD

**Issue by HenrikBengtsson** [hiclib/pastis#5]
Instead of using:

```
# CHANGEME: 
# The following is the directory where IPOPT is installed
IPOPTPATH = /home/nelle/.local
```

in the two src/(MDS|PM)/Makefile:s, I suggest that you use:

```
# The following is the directory where IPOPT is installed
IPOPTPATH = $(abspath $(dir $(abspath $(dir $(shell which ipopt)))))
```

This should located the Ipopt path automagically for most users.

**Comment by NelleV** [comment]
I've remove the IPOPT dependency, so the installation should be much much easier.
