### ISSUE TITLE
questions about running the test

### ISSUE THREAD

**Issue by PACOYANG2019** [hiclib/pastis#54]
when I run below:
python test_config.py

The error occur like this:
  File "test_config.py", line 1, in <module>
    from pastis import config
  File "/home/yang/.local/lib/python2.7/site-packages/pastis/__init__.py", line 4
    f1rom . import fastio

**Comment by NelleV** [comment]
Hello,
The file `test_config.py` is not meant to be run by calling python directly on it. These are unit tests as part of the package, and should be run with a test runner or collector such as pytest or nosetest.
See https://docs.python-guide.org/writing/tests/ for more information on unit tests.
Thanks,
Nelle

**Comment by PACOYANG2019** [comment]
Thank you for your attention. If there has a document with more details about using  pastis? I want to konw how to use it to deal with a HIC data. And the error I'ved mentioned occured when I run below: pastis-mds example. Thanks a lot.
