### ISSUE TITLE
IOError: ./2.PM2.structure.pdb.txt not found.

### ISSUE THREAD

**Issue by drbinguo** [hiclib/pastis#55]
There was some issue in my pastis, when I use the command " pastis-pm2 ." in the example.
It shows that " IOError: ./2.PM2.structure.pdb.txt not found".
But there were "2.PM2.structure.pdb.temp.pdb" and "2.PM2.structure.pdb.temp.txt" in the directory "pasits/example".

Any help is appreciated.

Thank you

**Comment by NelleV** [comment]
Hello,
The temp files were written every 10 or 100 iterations in an old version of the code. I'm not sure I understand why you are getting the IOError on the other hand. Do you have the whole traceback?
Thanks,
nelle

**Comment by drbinguo** [comment]
Number of Iterations .... : 45909
It shows that "Restoration phase converged to a feasible point that is unacceptable to the filter for the original problem. Restoration phase in the restor ation phase failed." in the file "2.PM2.log“.
Number of objective function evaluations = 198573
Number of objective gradient evaluations = 45834
Number of equality constratint evaluations =0
Number of inequality constraint evaluations = 198573
Number of equality constraint Jacobian evaluations =0
Number of inequality constraint Jacobian evaluations = 45941
Number of Lagrangian Hessian evaluations =0
Total CPU secs in IPOPT(w/o function evaluations)=83.574
Total CPU secs in NLP function evaluations = 1595.183
Objective value 
f(x*)=-5.339160e+06

Thanks a lot!

**Comment by NelleV** [comment]
Hello,
I'm afraid this is an old version of the code : I've stopped using IPOPT as it resulted in too many convergence issues. Could you update this?
Thanks,

**Comment by drbinguo** [comment]
OK, Let me have a try. 
Thank you for your kindness.
