### ISSUE TITLE
Many points located at (100,100,100)

### ISSUE THREAD

**Issue by sirusb** [hiclib/pastis#9]
Hi,
first thanks for the package it is really nice,
just recently when I started using the package I always run into cases where the last bins (some times whole chromosomes) are all located at the position (100,100,100) which is normally the sphere boundary, if I am getting it right.
```
ATOM     10 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     11 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     12 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     13 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     14 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     15 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     16 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     17 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     18 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     19 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     20 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     21 O    EDG C         100.000 100.000 100.000  1.00 75.00
ATOM     22 N    NOD C         100.000 100.000 100.000  1.00 50.00
```

Do you have an idea on why it is happening ?

**Comment by NelleV** [comment]
Hello,

That could happen when some of the beads are associated to no interactions (the rows and columns of the data matrix for these entries is 0). In this case, if you add a constraint on the size of the nucleus, the optimization is just going to move these beads inside the sphere representing the nucleus). It happens quite often that telomeres, for mappability reason, do not have any data.

The PDB files contains a smoothed version of the inferred structure. You may want to check in the coordinate file that this is also the case for specifically the coordinates of the beads. The documentation is not very clear on these points, and I will update these as soon as possible.

Thanks,
Nelle

**Comment by sirusb** [comment]
Hi Nelle,
Thanks for your quick replay and the update of the code.
I updated my code according to your recent changes and it is working,
just sometimes, the last point is 100,100,100 even if lengths and the Hi-C matrix have the same size.
