### ISSUE TITLE
some problems pastis-pm2

### ISSUE THREAD

**Issue by jmdeer** [hiclib/pastis#91]
py:8: UserWarning: The API of this module is likely to change. Use only for testing purposes
  warnings.warn(
py:8: UserWarning: The API of this module is likely to change. Use only for testing purposes
  warnings.warn(
py:7: UserWarning: The module pastis.fastio is deprecated. The packaged iced has identical features and should be used instead. This module will be removed in version 0.5
  warnings.warn(
usage: pastis-pm2 [-h] N
pastis-pm2: error: the following arguments are required: N

**Comment by kuangzhuoran** [comment]
Hi, I met the same error
Do you fixed it?

**Comment by gesinecauer** [comment]
Hey @kuangzhuoran, would you mind sharing the commands you used to install PASTIS, as well as the specific command you used to run PASTIS?

**Comment by NelleV** [comment]
@kuangzhuoran You need to provide an argument to the command. I believe that if you type `pastis-pm2 -h` you will see the help function, which describes the argument expected by pastis-pm2.
